version: '3'
services:
  db:
    image: postgres:10.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: rm -f tmp/pids/server.pid
    volumes:
      - .:/sample_app
    ports:
      - "4000:4000"
    tty: true
    depends_on:
      - db
